# events {}

# http {
#     server {
#         listen 80;

#         location /api/v1/service1 {
#             proxy_pass http://backend1:5001;
#         }

#         location /api/v1/service2 {
#             proxy_pass http://backend2:5002;
#         }
#     }
# }
