events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-nginx:5001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /payments/ {
            proxy_pass http://payment-nginx:5002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /inventories/ {
            proxy_pass http://inventory-service:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /orders/ {
            proxy_pass http://order-service:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}