events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-nginx:5001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /alerts/ {
            proxy_pass http://alerts-nginx:5002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /products/ {
            proxy_pass http://products:8080/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}