version: 2

updates:
  - package-ecosystem: maven
    directory: /order-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - order-service
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /order-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - order-service
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: composer
    directory: /payment-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - payment-service

  - package-ecosystem: docker
    directory: /payment-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - payment-service
      - docker
