version: 2

updates:
  - package-ecosystem: maven
    directory: /order-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - order-service
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /order-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - order-service
      - docker

  - package-ecosystem: npm
    directory: /inventory-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - inventory-service
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /inventory-service
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - inventory-service
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
