sonar.projectKey=Davi3234_trabalho-devops
sonar.organization=Davi3234
sonar.projectName=payment-service

sonar.sources=app,routes,database
sonar.tests=tests
sonar.exclusions=vendor/**,bootstrap/**,storage/**,public/**,config/**,resources/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.sourceEncoding=UTF-8