spring.application.name=order-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

server.port=8080

springdoc.swagger-ui.enabled=${SWAGGER_ENABLED:false}
springdoc.api-docs.enabled=${SWAGGER_ENABLED:false}
springdoc.swagger-ui.path=/swagger-ui.html

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.access=unrestricted
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}

info.app.name=@project.artifactId@
info.app.version=@project.version@
management.info.env.enabled=true

info.build.imageTag=${DOCKER_IMAGE_TAG:unknown}
info.build.gitCommit=${GIT_COMMIT:unknown}
info.build.gitBranch=${GIT_BRANCH:unknown}
