spring.application.name=order-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

rabbitmq.queues.estoque-reserva-aprovou=order.estoque.reservado
rabbitmq.queues.estoque-reserva-falhou=order.reserva.falhou
rabbitmq.queues.pagamento-recusado=order.pagamento.recusado
rabbitmq.queues.pagamento-confirmado=order.pagamento.confirmado
rabbitmq.queues.entrega-despachada=order.entrega.despachada

server.port=8080
