apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-dev-config
  labels:
    app: order-service-dev
    environment: dev
data:
  SPRING_APPLICATION_NAME: order-service
  SPRING_PROFILES_ACTIVE: dev
  DB_URL: jdbc:postgresql://order-postgres-dev:5432/order
  SWAGGER_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info,metrics,prometheus
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: admin
  SPRING_RABBITMQ_PASSWORD: admin
