sonar.sources=app,routes,database
sonar.tests=tests
sonar.exclusions=vendor/**,bootstrap/**,storage/**,public/**,config/**,resources/**,\
app/Interfaces/Http/Controller/MetricsController.php,\
app/Interfaces/Http/Middleware/PrometheusMetricsMiddleware.php,\
app/Infrastructure/Service/PrometheusService.php,\
app/Providers/PrometheusServiceProvider.php,\
routes/**

sonar.coverage.exclusions=vendor/**,bootstrap/**,storage/**,public/**,config/**,resources/**,\
app/Interfaces/Http/Controller/MetricsController.php,\
app/Interfaces/Http/Middleware/PrometheusMetricsMiddleware.php,\
app/Infrastructure/Service/PrometheusService.php,\
app/Providers/PrometheusServiceProvider.php,\
routes/**

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=junit.xml
sonar.sourceEncoding=UTF-8
