apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inventory-service-dev
  labels:
    app: inventory-service-dev
    environment: dev
spec:
  ingressClassName: nginx
  rules:
    - host: dev.devops.local
      http:
        paths:
          - path: /estoque
            pathType: Prefix
            backend:
              service:
                name: inventory-service-dev
                port:
                  number: 3000
