apiVersion: v1
kind: Service
metadata:
  name: inventory-service-dev
  labels:
    app: inventory-service-dev
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: inventory-service-dev
  ports:
    - name: http
      port: 3000
      targetPort: http
