apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: order-service-dev
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - order-service-dev:8080
            labels:
              namespace: order-service

      - job_name: order-service-homol
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - order-service-homol:8080
            labels:
              namespace: order-service

      - job_name: payment-service-dev
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - payment-service-dev:8080
            labels:
              namespace: payment-service

      - job_name: payment-service-homol
        metrics_path: /actuator/prometheus
        static_configs:
          - targets:
              - payment-service-homol:8080
            labels:
              namespace: payment-service

      - job_name: inventory-service-dev
        metrics_path: /metrics
        static_configs:
          - targets:
              - inventory-service-dev:3000
            labels:
              namespace: inventory-service

      - job_name: inventory-service-homol
        metrics_path: /metrics
        static_configs:
          - targets:
              - inventory-service-homol:3000
            labels:
              namespace: inventory-service
