apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-homol-config
  labels:
    app: payment-service-homol
    environment: homol
data:
  APP_NAME: "Payment Service"
  APP_ENV: production
  APP_DEBUG: "false"
  APP_URL: "http://homol.devops.local"
  APP_TIMEZONE: UTC
  LOG_CHANNEL: stderr
  DB_CONNECTION: pgsql
  DB_HOST: payment-postgres-homol
  DB_PORT: "5432"
  DB_DATABASE: payment
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  PROMETHEUS_STORAGE: redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  SWAGGER_ENABLED: "false"
  PAYMENT_SERVICE_URL: "http://payment-service-homol:8080"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
